/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleAuthenticatedRouteRouteImport } from './routes/$locale/_authenticated/route'
import { Route as Localeerrors500RouteImport } from './routes/$locale/(errors)/500'
import { Route as Localeerrors404RouteImport } from './routes/$locale/(errors)/404'
import { Route as Localeerrors403RouteImport } from './routes/$locale/(errors)/403'
import { Route as Localeerrors401RouteImport } from './routes/$locale/(errors)/401'
import { Route as LocaleauthVerifyPhoneRouteImport } from './routes/$locale/(auth)/verify-phone'
import { Route as LocaleauthVerifyEmailRouteImport } from './routes/$locale/(auth)/verify-email'
import { Route as LocaleauthSoftwareTokenMfaRouteImport } from './routes/$locale/(auth)/software-token-mfa'
import { Route as LocaleauthSmsMfaRouteImport } from './routes/$locale/(auth)/sms-mfa'
import { Route as LocaleauthSelectMfaTypeRouteImport } from './routes/$locale/(auth)/select-mfa-type'
import { Route as LocaleauthRegisterRouteImport } from './routes/$locale/(auth)/register'
import { Route as LocaleauthPhoneRegisterRouteImport } from './routes/$locale/(auth)/phone-register'
import { Route as LocaleauthNewPasswordRequiredRouteImport } from './routes/$locale/(auth)/new-password-required'
import { Route as LocaleauthLoginRouteImport } from './routes/$locale/(auth)/login'
import { Route as LocaleauthForgotPasswordRouteImport } from './routes/$locale/(auth)/forgot-password'
import { Route as LocaleAuthenticatedDashboardSubAffiliatesRouteImport } from './routes/$locale/_authenticated/dashboard/sub-affiliates'
import { Route as LocaleAuthenticatedDashboardSettingsRouteImport } from './routes/$locale/_authenticated/dashboard/settings'
import { Route as LocaleAuthenticatedDashboardReferralsRouteImport } from './routes/$locale/_authenticated/dashboard/referrals'
import { Route as LocaleAuthenticatedDashboardPerformanceRouteImport } from './routes/$locale/_authenticated/dashboard/performance'
import { Route as LocaleAuthenticatedDashboardPayoutsRouteImport } from './routes/$locale/_authenticated/dashboard/payouts'
import { Route as LocaleAuthenticatedDashboardOverviewRouteImport } from './routes/$locale/_authenticated/dashboard/overview'
import { Route as LocaleAuthenticatedDashboardLinksRouteImport } from './routes/$locale/_authenticated/dashboard/links'
import { Route as LocaleAuthenticatedDashboardEarningsRouteImport } from './routes/$locale/_authenticated/dashboard/earnings'
import { Route as LocaleAuthenticatedDashboardCampaignsRouteImport } from './routes/$locale/_authenticated/dashboard/campaigns'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAuthenticatedRouteRoute =
  LocaleAuthenticatedRouteRouteImport.update({
    id: '/$locale/_authenticated',
    path: '/$locale',
    getParentRoute: () => rootRouteImport,
  } as any)
const Localeerrors500Route = Localeerrors500RouteImport.update({
  id: '/$locale/(errors)/500',
  path: '/$locale/500',
  getParentRoute: () => rootRouteImport,
} as any)
const Localeerrors404Route = Localeerrors404RouteImport.update({
  id: '/$locale/(errors)/404',
  path: '/$locale/404',
  getParentRoute: () => rootRouteImport,
} as any)
const Localeerrors403Route = Localeerrors403RouteImport.update({
  id: '/$locale/(errors)/403',
  path: '/$locale/403',
  getParentRoute: () => rootRouteImport,
} as any)
const Localeerrors401Route = Localeerrors401RouteImport.update({
  id: '/$locale/(errors)/401',
  path: '/$locale/401',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleauthVerifyPhoneRoute = LocaleauthVerifyPhoneRouteImport.update({
  id: '/$locale/(auth)/verify-phone',
  path: '/$locale/verify-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleauthVerifyEmailRoute = LocaleauthVerifyEmailRouteImport.update({
  id: '/$locale/(auth)/verify-email',
  path: '/$locale/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleauthSoftwareTokenMfaRoute =
  LocaleauthSoftwareTokenMfaRouteImport.update({
    id: '/$locale/(auth)/software-token-mfa',
    path: '/$locale/software-token-mfa',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleauthSmsMfaRoute = LocaleauthSmsMfaRouteImport.update({
  id: '/$locale/(auth)/sms-mfa',
  path: '/$locale/sms-mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleauthSelectMfaTypeRoute = LocaleauthSelectMfaTypeRouteImport.update({
  id: '/$locale/(auth)/select-mfa-type',
  path: '/$locale/select-mfa-type',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleauthRegisterRoute = LocaleauthRegisterRouteImport.update({
  id: '/$locale/(auth)/register',
  path: '/$locale/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleauthPhoneRegisterRoute = LocaleauthPhoneRegisterRouteImport.update({
  id: '/$locale/(auth)/phone-register',
  path: '/$locale/phone-register',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleauthNewPasswordRequiredRoute =
  LocaleauthNewPasswordRequiredRouteImport.update({
    id: '/$locale/(auth)/new-password-required',
    path: '/$locale/new-password-required',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleauthLoginRoute = LocaleauthLoginRouteImport.update({
  id: '/$locale/(auth)/login',
  path: '/$locale/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleauthForgotPasswordRoute =
  LocaleauthForgotPasswordRouteImport.update({
    id: '/$locale/(auth)/forgot-password',
    path: '/$locale/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleAuthenticatedDashboardSubAffiliatesRoute =
  LocaleAuthenticatedDashboardSubAffiliatesRouteImport.update({
    id: '/dashboard/sub-affiliates',
    path: '/dashboard/sub-affiliates',
    getParentRoute: () => LocaleAuthenticatedRouteRoute,
  } as any)
const LocaleAuthenticatedDashboardSettingsRoute =
  LocaleAuthenticatedDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => LocaleAuthenticatedRouteRoute,
  } as any)
const LocaleAuthenticatedDashboardReferralsRoute =
  LocaleAuthenticatedDashboardReferralsRouteImport.update({
    id: '/dashboard/referrals',
    path: '/dashboard/referrals',
    getParentRoute: () => LocaleAuthenticatedRouteRoute,
  } as any)
const LocaleAuthenticatedDashboardPerformanceRoute =
  LocaleAuthenticatedDashboardPerformanceRouteImport.update({
    id: '/dashboard/performance',
    path: '/dashboard/performance',
    getParentRoute: () => LocaleAuthenticatedRouteRoute,
  } as any)
const LocaleAuthenticatedDashboardPayoutsRoute =
  LocaleAuthenticatedDashboardPayoutsRouteImport.update({
    id: '/dashboard/payouts',
    path: '/dashboard/payouts',
    getParentRoute: () => LocaleAuthenticatedRouteRoute,
  } as any)
const LocaleAuthenticatedDashboardOverviewRoute =
  LocaleAuthenticatedDashboardOverviewRouteImport.update({
    id: '/dashboard/overview',
    path: '/dashboard/overview',
    getParentRoute: () => LocaleAuthenticatedRouteRoute,
  } as any)
const LocaleAuthenticatedDashboardLinksRoute =
  LocaleAuthenticatedDashboardLinksRouteImport.update({
    id: '/dashboard/links',
    path: '/dashboard/links',
    getParentRoute: () => LocaleAuthenticatedRouteRoute,
  } as any)
const LocaleAuthenticatedDashboardEarningsRoute =
  LocaleAuthenticatedDashboardEarningsRouteImport.update({
    id: '/dashboard/earnings',
    path: '/dashboard/earnings',
    getParentRoute: () => LocaleAuthenticatedRouteRoute,
  } as any)
const LocaleAuthenticatedDashboardCampaignsRoute =
  LocaleAuthenticatedDashboardCampaignsRouteImport.update({
    id: '/dashboard/campaigns',
    path: '/dashboard/campaigns',
    getParentRoute: () => LocaleAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleAuthenticatedRouteRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/forgot-password': typeof LocaleauthForgotPasswordRoute
  '/$locale/login': typeof LocaleauthLoginRoute
  '/$locale/new-password-required': typeof LocaleauthNewPasswordRequiredRoute
  '/$locale/phone-register': typeof LocaleauthPhoneRegisterRoute
  '/$locale/register': typeof LocaleauthRegisterRoute
  '/$locale/select-mfa-type': typeof LocaleauthSelectMfaTypeRoute
  '/$locale/sms-mfa': typeof LocaleauthSmsMfaRoute
  '/$locale/software-token-mfa': typeof LocaleauthSoftwareTokenMfaRoute
  '/$locale/verify-email': typeof LocaleauthVerifyEmailRoute
  '/$locale/verify-phone': typeof LocaleauthVerifyPhoneRoute
  '/$locale/401': typeof Localeerrors401Route
  '/$locale/403': typeof Localeerrors403Route
  '/$locale/404': typeof Localeerrors404Route
  '/$locale/500': typeof Localeerrors500Route
  '/$locale/dashboard/campaigns': typeof LocaleAuthenticatedDashboardCampaignsRoute
  '/$locale/dashboard/earnings': typeof LocaleAuthenticatedDashboardEarningsRoute
  '/$locale/dashboard/links': typeof LocaleAuthenticatedDashboardLinksRoute
  '/$locale/dashboard/overview': typeof LocaleAuthenticatedDashboardOverviewRoute
  '/$locale/dashboard/payouts': typeof LocaleAuthenticatedDashboardPayoutsRoute
  '/$locale/dashboard/performance': typeof LocaleAuthenticatedDashboardPerformanceRoute
  '/$locale/dashboard/referrals': typeof LocaleAuthenticatedDashboardReferralsRoute
  '/$locale/dashboard/settings': typeof LocaleAuthenticatedDashboardSettingsRoute
  '/$locale/dashboard/sub-affiliates': typeof LocaleAuthenticatedDashboardSubAffiliatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/forgot-password': typeof LocaleauthForgotPasswordRoute
  '/$locale/login': typeof LocaleauthLoginRoute
  '/$locale/new-password-required': typeof LocaleauthNewPasswordRequiredRoute
  '/$locale/phone-register': typeof LocaleauthPhoneRegisterRoute
  '/$locale/register': typeof LocaleauthRegisterRoute
  '/$locale/select-mfa-type': typeof LocaleauthSelectMfaTypeRoute
  '/$locale/sms-mfa': typeof LocaleauthSmsMfaRoute
  '/$locale/software-token-mfa': typeof LocaleauthSoftwareTokenMfaRoute
  '/$locale/verify-email': typeof LocaleauthVerifyEmailRoute
  '/$locale/verify-phone': typeof LocaleauthVerifyPhoneRoute
  '/$locale/401': typeof Localeerrors401Route
  '/$locale/403': typeof Localeerrors403Route
  '/$locale/404': typeof Localeerrors404Route
  '/$locale/500': typeof Localeerrors500Route
  '/$locale/dashboard/campaigns': typeof LocaleAuthenticatedDashboardCampaignsRoute
  '/$locale/dashboard/earnings': typeof LocaleAuthenticatedDashboardEarningsRoute
  '/$locale/dashboard/links': typeof LocaleAuthenticatedDashboardLinksRoute
  '/$locale/dashboard/overview': typeof LocaleAuthenticatedDashboardOverviewRoute
  '/$locale/dashboard/payouts': typeof LocaleAuthenticatedDashboardPayoutsRoute
  '/$locale/dashboard/performance': typeof LocaleAuthenticatedDashboardPerformanceRoute
  '/$locale/dashboard/referrals': typeof LocaleAuthenticatedDashboardReferralsRoute
  '/$locale/dashboard/settings': typeof LocaleAuthenticatedDashboardSettingsRoute
  '/$locale/dashboard/sub-affiliates': typeof LocaleAuthenticatedDashboardSubAffiliatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale/_authenticated': typeof LocaleAuthenticatedRouteRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/(auth)/forgot-password': typeof LocaleauthForgotPasswordRoute
  '/$locale/(auth)/login': typeof LocaleauthLoginRoute
  '/$locale/(auth)/new-password-required': typeof LocaleauthNewPasswordRequiredRoute
  '/$locale/(auth)/phone-register': typeof LocaleauthPhoneRegisterRoute
  '/$locale/(auth)/register': typeof LocaleauthRegisterRoute
  '/$locale/(auth)/select-mfa-type': typeof LocaleauthSelectMfaTypeRoute
  '/$locale/(auth)/sms-mfa': typeof LocaleauthSmsMfaRoute
  '/$locale/(auth)/software-token-mfa': typeof LocaleauthSoftwareTokenMfaRoute
  '/$locale/(auth)/verify-email': typeof LocaleauthVerifyEmailRoute
  '/$locale/(auth)/verify-phone': typeof LocaleauthVerifyPhoneRoute
  '/$locale/(errors)/401': typeof Localeerrors401Route
  '/$locale/(errors)/403': typeof Localeerrors403Route
  '/$locale/(errors)/404': typeof Localeerrors404Route
  '/$locale/(errors)/500': typeof Localeerrors500Route
  '/$locale/_authenticated/dashboard/campaigns': typeof LocaleAuthenticatedDashboardCampaignsRoute
  '/$locale/_authenticated/dashboard/earnings': typeof LocaleAuthenticatedDashboardEarningsRoute
  '/$locale/_authenticated/dashboard/links': typeof LocaleAuthenticatedDashboardLinksRoute
  '/$locale/_authenticated/dashboard/overview': typeof LocaleAuthenticatedDashboardOverviewRoute
  '/$locale/_authenticated/dashboard/payouts': typeof LocaleAuthenticatedDashboardPayoutsRoute
  '/$locale/_authenticated/dashboard/performance': typeof LocaleAuthenticatedDashboardPerformanceRoute
  '/$locale/_authenticated/dashboard/referrals': typeof LocaleAuthenticatedDashboardReferralsRoute
  '/$locale/_authenticated/dashboard/settings': typeof LocaleAuthenticatedDashboardSettingsRoute
  '/$locale/_authenticated/dashboard/sub-affiliates': typeof LocaleAuthenticatedDashboardSubAffiliatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/'
    | '/$locale/forgot-password'
    | '/$locale/login'
    | '/$locale/new-password-required'
    | '/$locale/phone-register'
    | '/$locale/register'
    | '/$locale/select-mfa-type'
    | '/$locale/sms-mfa'
    | '/$locale/software-token-mfa'
    | '/$locale/verify-email'
    | '/$locale/verify-phone'
    | '/$locale/401'
    | '/$locale/403'
    | '/$locale/404'
    | '/$locale/500'
    | '/$locale/dashboard/campaigns'
    | '/$locale/dashboard/earnings'
    | '/$locale/dashboard/links'
    | '/$locale/dashboard/overview'
    | '/$locale/dashboard/payouts'
    | '/$locale/dashboard/performance'
    | '/$locale/dashboard/referrals'
    | '/$locale/dashboard/settings'
    | '/$locale/dashboard/sub-affiliates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/forgot-password'
    | '/$locale/login'
    | '/$locale/new-password-required'
    | '/$locale/phone-register'
    | '/$locale/register'
    | '/$locale/select-mfa-type'
    | '/$locale/sms-mfa'
    | '/$locale/software-token-mfa'
    | '/$locale/verify-email'
    | '/$locale/verify-phone'
    | '/$locale/401'
    | '/$locale/403'
    | '/$locale/404'
    | '/$locale/500'
    | '/$locale/dashboard/campaigns'
    | '/$locale/dashboard/earnings'
    | '/$locale/dashboard/links'
    | '/$locale/dashboard/overview'
    | '/$locale/dashboard/payouts'
    | '/$locale/dashboard/performance'
    | '/$locale/dashboard/referrals'
    | '/$locale/dashboard/settings'
    | '/$locale/dashboard/sub-affiliates'
  id:
    | '__root__'
    | '/'
    | '/$locale/_authenticated'
    | '/$locale/'
    | '/$locale/(auth)/forgot-password'
    | '/$locale/(auth)/login'
    | '/$locale/(auth)/new-password-required'
    | '/$locale/(auth)/phone-register'
    | '/$locale/(auth)/register'
    | '/$locale/(auth)/select-mfa-type'
    | '/$locale/(auth)/sms-mfa'
    | '/$locale/(auth)/software-token-mfa'
    | '/$locale/(auth)/verify-email'
    | '/$locale/(auth)/verify-phone'
    | '/$locale/(errors)/401'
    | '/$locale/(errors)/403'
    | '/$locale/(errors)/404'
    | '/$locale/(errors)/500'
    | '/$locale/_authenticated/dashboard/campaigns'
    | '/$locale/_authenticated/dashboard/earnings'
    | '/$locale/_authenticated/dashboard/links'
    | '/$locale/_authenticated/dashboard/overview'
    | '/$locale/_authenticated/dashboard/payouts'
    | '/$locale/_authenticated/dashboard/performance'
    | '/$locale/_authenticated/dashboard/referrals'
    | '/$locale/_authenticated/dashboard/settings'
    | '/$locale/_authenticated/dashboard/sub-affiliates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleAuthenticatedRouteRoute: typeof LocaleAuthenticatedRouteRouteWithChildren
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleauthForgotPasswordRoute: typeof LocaleauthForgotPasswordRoute
  LocaleauthLoginRoute: typeof LocaleauthLoginRoute
  LocaleauthNewPasswordRequiredRoute: typeof LocaleauthNewPasswordRequiredRoute
  LocaleauthPhoneRegisterRoute: typeof LocaleauthPhoneRegisterRoute
  LocaleauthRegisterRoute: typeof LocaleauthRegisterRoute
  LocaleauthSelectMfaTypeRoute: typeof LocaleauthSelectMfaTypeRoute
  LocaleauthSmsMfaRoute: typeof LocaleauthSmsMfaRoute
  LocaleauthSoftwareTokenMfaRoute: typeof LocaleauthSoftwareTokenMfaRoute
  LocaleauthVerifyEmailRoute: typeof LocaleauthVerifyEmailRoute
  LocaleauthVerifyPhoneRoute: typeof LocaleauthVerifyPhoneRoute
  Localeerrors401Route: typeof Localeerrors401Route
  Localeerrors403Route: typeof Localeerrors403Route
  Localeerrors404Route: typeof Localeerrors404Route
  Localeerrors500Route: typeof Localeerrors500Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_authenticated': {
      id: '/$locale/_authenticated'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleAuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/(errors)/500': {
      id: '/$locale/(errors)/500'
      path: '/$locale/500'
      fullPath: '/$locale/500'
      preLoaderRoute: typeof Localeerrors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/(errors)/404': {
      id: '/$locale/(errors)/404'
      path: '/$locale/404'
      fullPath: '/$locale/404'
      preLoaderRoute: typeof Localeerrors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/(errors)/403': {
      id: '/$locale/(errors)/403'
      path: '/$locale/403'
      fullPath: '/$locale/403'
      preLoaderRoute: typeof Localeerrors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/(errors)/401': {
      id: '/$locale/(errors)/401'
      path: '/$locale/401'
      fullPath: '/$locale/401'
      preLoaderRoute: typeof Localeerrors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/(auth)/verify-phone': {
      id: '/$locale/(auth)/verify-phone'
      path: '/$locale/verify-phone'
      fullPath: '/$locale/verify-phone'
      preLoaderRoute: typeof LocaleauthVerifyPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/(auth)/verify-email': {
      id: '/$locale/(auth)/verify-email'
      path: '/$locale/verify-email'
      fullPath: '/$locale/verify-email'
      preLoaderRoute: typeof LocaleauthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/(auth)/software-token-mfa': {
      id: '/$locale/(auth)/software-token-mfa'
      path: '/$locale/software-token-mfa'
      fullPath: '/$locale/software-token-mfa'
      preLoaderRoute: typeof LocaleauthSoftwareTokenMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/(auth)/sms-mfa': {
      id: '/$locale/(auth)/sms-mfa'
      path: '/$locale/sms-mfa'
      fullPath: '/$locale/sms-mfa'
      preLoaderRoute: typeof LocaleauthSmsMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/(auth)/select-mfa-type': {
      id: '/$locale/(auth)/select-mfa-type'
      path: '/$locale/select-mfa-type'
      fullPath: '/$locale/select-mfa-type'
      preLoaderRoute: typeof LocaleauthSelectMfaTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/(auth)/register': {
      id: '/$locale/(auth)/register'
      path: '/$locale/register'
      fullPath: '/$locale/register'
      preLoaderRoute: typeof LocaleauthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/(auth)/phone-register': {
      id: '/$locale/(auth)/phone-register'
      path: '/$locale/phone-register'
      fullPath: '/$locale/phone-register'
      preLoaderRoute: typeof LocaleauthPhoneRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/(auth)/new-password-required': {
      id: '/$locale/(auth)/new-password-required'
      path: '/$locale/new-password-required'
      fullPath: '/$locale/new-password-required'
      preLoaderRoute: typeof LocaleauthNewPasswordRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/(auth)/login': {
      id: '/$locale/(auth)/login'
      path: '/$locale/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleauthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/(auth)/forgot-password': {
      id: '/$locale/(auth)/forgot-password'
      path: '/$locale/forgot-password'
      fullPath: '/$locale/forgot-password'
      preLoaderRoute: typeof LocaleauthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_authenticated/dashboard/sub-affiliates': {
      id: '/$locale/_authenticated/dashboard/sub-affiliates'
      path: '/dashboard/sub-affiliates'
      fullPath: '/$locale/dashboard/sub-affiliates'
      preLoaderRoute: typeof LocaleAuthenticatedDashboardSubAffiliatesRouteImport
      parentRoute: typeof LocaleAuthenticatedRouteRoute
    }
    '/$locale/_authenticated/dashboard/settings': {
      id: '/$locale/_authenticated/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/$locale/dashboard/settings'
      preLoaderRoute: typeof LocaleAuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof LocaleAuthenticatedRouteRoute
    }
    '/$locale/_authenticated/dashboard/referrals': {
      id: '/$locale/_authenticated/dashboard/referrals'
      path: '/dashboard/referrals'
      fullPath: '/$locale/dashboard/referrals'
      preLoaderRoute: typeof LocaleAuthenticatedDashboardReferralsRouteImport
      parentRoute: typeof LocaleAuthenticatedRouteRoute
    }
    '/$locale/_authenticated/dashboard/performance': {
      id: '/$locale/_authenticated/dashboard/performance'
      path: '/dashboard/performance'
      fullPath: '/$locale/dashboard/performance'
      preLoaderRoute: typeof LocaleAuthenticatedDashboardPerformanceRouteImport
      parentRoute: typeof LocaleAuthenticatedRouteRoute
    }
    '/$locale/_authenticated/dashboard/payouts': {
      id: '/$locale/_authenticated/dashboard/payouts'
      path: '/dashboard/payouts'
      fullPath: '/$locale/dashboard/payouts'
      preLoaderRoute: typeof LocaleAuthenticatedDashboardPayoutsRouteImport
      parentRoute: typeof LocaleAuthenticatedRouteRoute
    }
    '/$locale/_authenticated/dashboard/overview': {
      id: '/$locale/_authenticated/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/$locale/dashboard/overview'
      preLoaderRoute: typeof LocaleAuthenticatedDashboardOverviewRouteImport
      parentRoute: typeof LocaleAuthenticatedRouteRoute
    }
    '/$locale/_authenticated/dashboard/links': {
      id: '/$locale/_authenticated/dashboard/links'
      path: '/dashboard/links'
      fullPath: '/$locale/dashboard/links'
      preLoaderRoute: typeof LocaleAuthenticatedDashboardLinksRouteImport
      parentRoute: typeof LocaleAuthenticatedRouteRoute
    }
    '/$locale/_authenticated/dashboard/earnings': {
      id: '/$locale/_authenticated/dashboard/earnings'
      path: '/dashboard/earnings'
      fullPath: '/$locale/dashboard/earnings'
      preLoaderRoute: typeof LocaleAuthenticatedDashboardEarningsRouteImport
      parentRoute: typeof LocaleAuthenticatedRouteRoute
    }
    '/$locale/_authenticated/dashboard/campaigns': {
      id: '/$locale/_authenticated/dashboard/campaigns'
      path: '/dashboard/campaigns'
      fullPath: '/$locale/dashboard/campaigns'
      preLoaderRoute: typeof LocaleAuthenticatedDashboardCampaignsRouteImport
      parentRoute: typeof LocaleAuthenticatedRouteRoute
    }
  }
}

interface LocaleAuthenticatedRouteRouteChildren {
  LocaleAuthenticatedDashboardCampaignsRoute: typeof LocaleAuthenticatedDashboardCampaignsRoute
  LocaleAuthenticatedDashboardEarningsRoute: typeof LocaleAuthenticatedDashboardEarningsRoute
  LocaleAuthenticatedDashboardLinksRoute: typeof LocaleAuthenticatedDashboardLinksRoute
  LocaleAuthenticatedDashboardOverviewRoute: typeof LocaleAuthenticatedDashboardOverviewRoute
  LocaleAuthenticatedDashboardPayoutsRoute: typeof LocaleAuthenticatedDashboardPayoutsRoute
  LocaleAuthenticatedDashboardPerformanceRoute: typeof LocaleAuthenticatedDashboardPerformanceRoute
  LocaleAuthenticatedDashboardReferralsRoute: typeof LocaleAuthenticatedDashboardReferralsRoute
  LocaleAuthenticatedDashboardSettingsRoute: typeof LocaleAuthenticatedDashboardSettingsRoute
  LocaleAuthenticatedDashboardSubAffiliatesRoute: typeof LocaleAuthenticatedDashboardSubAffiliatesRoute
}

const LocaleAuthenticatedRouteRouteChildren: LocaleAuthenticatedRouteRouteChildren =
  {
    LocaleAuthenticatedDashboardCampaignsRoute:
      LocaleAuthenticatedDashboardCampaignsRoute,
    LocaleAuthenticatedDashboardEarningsRoute:
      LocaleAuthenticatedDashboardEarningsRoute,
    LocaleAuthenticatedDashboardLinksRoute:
      LocaleAuthenticatedDashboardLinksRoute,
    LocaleAuthenticatedDashboardOverviewRoute:
      LocaleAuthenticatedDashboardOverviewRoute,
    LocaleAuthenticatedDashboardPayoutsRoute:
      LocaleAuthenticatedDashboardPayoutsRoute,
    LocaleAuthenticatedDashboardPerformanceRoute:
      LocaleAuthenticatedDashboardPerformanceRoute,
    LocaleAuthenticatedDashboardReferralsRoute:
      LocaleAuthenticatedDashboardReferralsRoute,
    LocaleAuthenticatedDashboardSettingsRoute:
      LocaleAuthenticatedDashboardSettingsRoute,
    LocaleAuthenticatedDashboardSubAffiliatesRoute:
      LocaleAuthenticatedDashboardSubAffiliatesRoute,
  }

const LocaleAuthenticatedRouteRouteWithChildren =
  LocaleAuthenticatedRouteRoute._addFileChildren(
    LocaleAuthenticatedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleAuthenticatedRouteRoute: LocaleAuthenticatedRouteRouteWithChildren,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleauthForgotPasswordRoute: LocaleauthForgotPasswordRoute,
  LocaleauthLoginRoute: LocaleauthLoginRoute,
  LocaleauthNewPasswordRequiredRoute: LocaleauthNewPasswordRequiredRoute,
  LocaleauthPhoneRegisterRoute: LocaleauthPhoneRegisterRoute,
  LocaleauthRegisterRoute: LocaleauthRegisterRoute,
  LocaleauthSelectMfaTypeRoute: LocaleauthSelectMfaTypeRoute,
  LocaleauthSmsMfaRoute: LocaleauthSmsMfaRoute,
  LocaleauthSoftwareTokenMfaRoute: LocaleauthSoftwareTokenMfaRoute,
  LocaleauthVerifyEmailRoute: LocaleauthVerifyEmailRoute,
  LocaleauthVerifyPhoneRoute: LocaleauthVerifyPhoneRoute,
  Localeerrors401Route: Localeerrors401Route,
  Localeerrors403Route: Localeerrors403Route,
  Localeerrors404Route: Localeerrors404Route,
  Localeerrors500Route: Localeerrors500Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
